config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  resources :feedbacks
  get 'new_feedback' => 'feedbacks#new'
  get 'sessions/new'
  get 'administrators/new'
  root 'administrator_pages#home'
  #get 'administrator_pages/home'
  get 'sensor_info' => 'sensors#sensor_info'
  get  '/help',    to: 'administrator_pages#help'
  get  '/about',   to: 'administrator_pages#about'
  get  '/contact', to: 'administrator_pages#contact'
  get  '/signup',  to: 'administrators#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/test', to: 'sessions#test'
  resources :administrators
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  #root 'home#home'
  #get 'home/home'
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  resources :sensors
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/sensor.rb
class Sensor < ActiveRecord::Base 
  # include ActiveModel::Validations::Callbacks


  
  # VALID_LOCATION_REGEX = /\A^[-+]?([1-8]?\d(\.\d+)?|90(\.0+)?),\s*[-+]?(180(\.0+)?|((1[0-7]\d)|([1-9]?\d))(\.\d+)?)$\z/
  # validates :location, presence: true, 
  #           length: {maximum: 50}, 
  #           format: { with: VALID_LOCATION_REGEX }

  # validate study_area_id is greater than 0 if present
  # validates :study_area_id, 
  #           numericality: { greater_than: 0, if: proc { |s| s.study_area_id.present? }}
  # sensor_types = ["camera", "air quality", "induction loop", "counter"]
  # validates :sensor_type, 
  #           inclusion: { in: sensor_types}
  def address
    if latitude != nil && longitude != nil
      nil
    elsif street != nil
      [street, "Boston", "Massachusetts", "United States"].compact.join(', ')
    elsif location != nil 
      location
    else
      nil
    end
  end

  geocoded_by :address
  before_validation :geocode, if: ->(obj){obj.address.present? && !(obj.latitude.present? && obj.longitude.present?)}
  # if(:street != nil)
  #   geocoded_by :address
  #   after_validation :geocode
  # else
  # before_validation: :geocode, if: :
  before_validation :reverse_geocode, if: ->(obj){!obj.location.present?}
  reverse_geocoded_by :latitude, :longitude, :address => :location
  after_validation :reverse_geocode 
  
end

app/controllers/sensors_controller.rb
class SensorsController < ApplicationController
  before_action :set_sensor, only: [:show, :edit, :update, :destroy]

  # GET /sensors
  # GET /sensors.json
  def index
    @sensors = Sensor.all
    #render json: @sensors
  end

  # GET /sensors/1
  # GET /sensors/1.json
  def show
  end

  # GET /sensors/new
  def new
    @sensor = Sensor.new
  end

  # GET /sensors/1/edit
  def edit
  end

  # POST /sensors
  # POST /sensors.json
  def create
    @sensor = Sensor.new(sensor_params)

    respond_to do |format|
      if @sensor.save
        format.html { redirect_to @sensor, notice: 'Sensor was successfully created.' }
        format.json { render :show, status: :created, location: @sensor }
      else
        format.html { render :new }
        format.json { render json: @sensor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sensors/1
  # PATCH/PUT /sensors/1.json
  def update
    respond_to do |format|
      if @sensor.update(sensor_params)
        format.html { redirect_to @sensor, notice: 'Sensor was successfully updated.' }
        format.json { render :show, status: :ok, location: @sensor }
      else
        format.html { render :edit }
        format.json { render json: @sensor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sensors/1
  # DELETE /sensors/1.json
  def destroy
    @sensor.destroy
    respond_to do |format|
      format.html { redirect_to sensors_url, notice: 'Sensor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def sensor_info
    @sensor = Sensor.find(params[:si])
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sensor
      @sensor = Sensor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sensor_params
      params.require(:sensor).permit(:type)
    end
end

app/helpers/sensors_helper.rb
module SensorsHelper
end

app/views/sensors/_form.html.erb
<%= form_with(model: sensor, local: true) do |form| %>
  <% if sensor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sensor.errors.count, "error") %> prohibited this sensor from being saved:</h2>

      <ul>
        <% sensor.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :type %>
    <%= form.text_field :type %>
    <%= form.check_box :hidden %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sensors/edit.html.erb
<h1>Editing Sensor</h1>

<%= render 'form', sensor: @sensor %>

<%= link_to 'Show', @sensor %> |
<%= link_to 'Back', sensors_path %>

app/views/sensors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sensors</h1>

<table>
  <thead>
    <tr>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sensors.each do |sensor| %>
      <tr>
        <td><%= sensor.ownership %></td>
        <td><%= sensor.sensor_type %></td>
        <td><%= link_to 'Show', sensor %></td>
        <td><%= link_to 'Edit', edit_sensor_path(sensor) %></td>
        <td><%= link_to 'Destroy', sensor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sensor', new_sensor_path %>

app/views/sensors/new.html.erb
<h1>New Sensor</h1>

<%= render 'form', sensor: @sensor %>

<%= link_to 'Back', sensors_path %>

app/views/sensors/sensor_info.js.erb
$('#searchInfo').attr('name', <%= j @sensor.id %>);
$('#feedback_topic').val('Sensor - ' + <%= j @sensor.id %>);
$('#searchInfo').html(
    '<div class = "id_info">' + 
        'Sensor ' + '<%= j @sensor.id %>' +
    '</div>'
);
$('#searchInfo').append(
    '<div class = "type_info">' +
        '<%= j @sensor.sensor_type %>' +
    '</div>'
);
$('#searchInfo').append(
    '<div class = "location_info">' +
        '<%= j @sensor.location %>' +
    '</div>'
);
$('#searchInfo').append(
    '<div class = "description-box"></div>'
)
<% if @sensor.owner != nil %>
    $('.description-box').append(
        '<div class = "owner_info">' +
            '<%= j @sensor.owner%>' +
        '</div>'
    );
<% else %>
    $('.description-box').append(
        '<div class = "owner_info">' +
            'Owner: ' + 'Owner not specified.' +
        '</div>'
    );
<% end %>
<% if @sensor.description != nil %>
    $('.description-box').append(
        '<div class = "description_info">' +
            'Comment: ' + '"' +'<%= j @sensor.description %>' + '"' +
        '</div>'
    );
<% else %>
    $('.description-box').append(
        '<div class = "description_info">' +
            'Comment: ' + 'No description specified.' + 
        '</div>'
    );
<% end %>

app/views/sensors/show.html.erb
<div class = "show-page">
<div class = "container">

  <div class = "row">
    <div class = "col-12 text-left">
      <h2>Sensor  <%= @sensor.sensor_id %></h2>
    </div>
  </div>

  <div class = "row">
    <div class = "col-12">
      <h3><%= @sensor.sensor_type %></h3>
    </div>
  </div>

  <div class = "row">
    <div class = "col-12">
      <h4><%= @sensor.location %></h4>
    </div>
  </div>

  <p>
  <p>

  <div class = "row">
    <div class = "col-6">
      <strong>Ownership</strong>
    </div>
    <div class = "col-6">
      <%= @sensor.owner %>
    </div>
  </div>

</div>
</div>