config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  resources :feedbacks
  get 'new_feedback' => 'feedbacks#new'
  get 'sessions/new'
  get 'administrators/new'
  root 'administrator_pages#home'
  #get 'administrator_pages/home'
  get 'sensor_info' => 'sensors#sensor_info'
  get  '/help',    to: 'administrator_pages#help'
  get  '/about',   to: 'administrator_pages#about'
  get  '/contact', to: 'administrator_pages#contact'
  get  '/signup',  to: 'administrators#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/test', to: 'sessions#test'
  resources :administrators
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  #root 'home#home'
  #get 'home/home'
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  resources :sensors
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_favicon.html.erb
<% %w(76 120 152 167 180).each do |size| %>
    <%= favicon_link_tag "cobtransparency_icon-#{size}x#{size}.png", rel: 'cobtransparency_icon', type: 'image/png', sizes: "#{size}x#{size}" %>
  <% end %>
  
  <% %w(16 32).each do |size| %>
    <%= favicon_link_tag "cobtransparency_icon-#{size}x#{size}.png", rel: 'icon', type: 'image/png', sizes: "#{size}x#{size}" %>
<% end %>

<link rel="apple-touch-icon" href="/cobtransparency_icon-180x180.png" />

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    This is a City <a href="https://www.boston.gov/">of Boston Project</a>
    by <a href="https://www.brandeis.edu/">students of Brandeis University</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <%-# <li><a href="https://news.railstutorial.org/">News</a></li> -%>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
  <script>
    $(function(){
      $(".hamburger").click(function(){
        $(".cob-navbar").toggleClass("opened");
      });
    });
    
  </script>
  
  <nav class="navbar navbar-fixed-top navbar-inverse">
    <div class = "nav-background">

    </div>
    <div class = "logo-area">
      <%= link_to image_tag("COB_B_white.png", height: '30'), root_path, id: "logo" %>
      <%= link_to "Transparency", root_path, id: "logo" %>
    </div>
       
    <button id = "infoBtn"> 
      <%= image_tag "info.png", size:"25x25"%>
    </button>
  <div id="myModal" class="modal">
    <div class="modal-content">
      
        <span class="close-button">&times;</span>
        <%= render 'layouts/user_manual' %>
      
    </div>
  </div>

<script>
var modal = document.getElementById("myModal");
var btn = document.getElementById("infoBtn");
var span = document.getElementsByClassName("close-button")[0];
btn.onclick = function() {
  modal.style.display = "block";
}
span.onclick = function() {
  modal.style.display = "none";
}

window.onclick = function(event) {
  if (event.target == modal) {
    modal.style.display = "none";
  }
}
</script>


    <div class = "hamburger">
      <%= image_tag("hamburger-bar.svg", size: "20x20", class:"hamburger-icon") %>
    </div>

    <div class = "cob-navbar">
      <div class = "cob-navbar-list">
        <%= link_to "About us", about_path, class: "navbar-link"%>
      </div>
        
      <% if logged_in? %>
        <div class = "cob-navbar-list">
          <%= link_to "Site Administration", '/admin', class: "navbar-link"%>
        </div>
        <div class = "cob-navbar-list">
          <%= link_to "Log out", logout_path, method: :delete, class: "navbar-link" %> 
        </div>
      <% else %>
        <div class = "cob-navbar-list">
          <%= link_to "Administrator? Log in", login_path, class: "navbar-link" %>
        </div>
      <% end %>
    </div>
    

</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/_user_manual.html.erb
<h4 class="instruction" style="font-weight:bold;">App instruction</h4><br>
<%= image_tag "main_annotation.png", :class => "instruction-img"%>

<div class="instruction">
  <h5 style="color:#ff9900; font-weight:bold;">&#9312; App title</h5>
  <ul><li>Click anytime to get back to the map</li></ul>

  <h5 style="color:red; font-weight:bold;">&#9313; Menu</h5>
  <ul><li>Click to expand to the full menu</li></ul>

  <h5 style="color:#1155cc; font-weight:bold;">&#9314; Map toggle</h5>
  <ul>
    <li><%= image_tag "map_plus.jpg", {:class => "custom-icons", :style => "height:25px; width:25px;"} %> Zoom in map</li>
    <li><%= image_tag "map_minus.jpg", {:class => "custom-icons", :style => "height:25px; width:25px;"} %> Zoom out map</li>
    <li><%= image_tag "map_location.jpg", {:class => "custom-icons", :style => "height:25px; width:25px;"} %> Show sensors around you</li>
    <li><%= image_tag "satellite-dish.svg", {:class => "custom-icons", :style => "height:25px; width:25px;"} %> Switch to terrain view</li>
  </ul>

  <h5 style="color:green; font-weight:bold;">&#9315; Sensor toggle</h5>
  <ul>
    <li><%= image_tag "neighborhood_line.svg", :class => "toggle_icon_img" %> Show/hide neighborhood lines</li>
    <li><%= image_tag "camera.svg", :class => "toggle_icon_img" %> Show/hide camera sensors</li>
    <li><%= image_tag "air_quality.svg", :class => "toggle_icon_img" %> Show/hide air quality sensors</li>
    <li><%= image_tag "counter.svg", :class => "toggle_icon_img" %> Show/hide counter sensors</li>
    <li><%= image_tag "antenna.svg", :class => "toggle_icon_img" %> Show/hide antenna sensors</li>
    <li><%= image_tag "other_sensor.svg", :class => "toggle_icon_img" %> Show/hide other sensors</li>
    <li><%= image_tag "arrow.jpg", :class => "toggle_icon_img" %> Show/hide sensor toggle</li>
  </ul>

  <h5 style="font-weight:bold;">&#9316; Search bar</h5>
  <ul><li>Search for addresses, neighborhoods and sensors</li></ul>
</div>


<br><hr><br>


<h4 class="instruction" style="font-weight:bold;">Save this app to your home screen</h4><br>
<div class="instruction">
  <h5>Click on the menu of your phone's browser</h5>
  <h5>Choose "Add to Home Screen"</h5>
  <h5>Click "Add"</h5>
</div>
<%= image_tag "download_annotation.png", :class => "instruction-img"%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src='https://api.mapbox.com/mapbox-gl-js/v1.8.0/mapbox-gl.js'></script>
    <link href='https://api.mapbox.com/mapbox-gl-js/v1.8.0/mapbox-gl.css' rel='stylesheet' />
    <script src="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v4.4.2/mapbox-gl-geocoder.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/es6-promise@4/dist/es6-promise.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/es6-promise@4/dist/es6-promise.auto.min.js"></script>
    <script src='https://api.mapbox.com/mapbox.js/plugins/turf/v3.0.11/turf.min.js'></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'%>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'%>
    <%= render 'layouts/shim' %>
    <%= render 'layouts/favicon' %>
    
    
  </head>
  
  <body>
    
    
    
    <%= render 'layouts/header' %>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
      
    
      <%= yield %>
    
    <%= debug(params) if Rails.env.development? %>

  </body>

</html>